<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Benedict Leonardi">
<meta name="dcterms.date" content="2026-07-08">

<title>Continuity or Rupture? A Text-as-Data Analysis of Vatican II and Comparative Doctrinal Change – Papal Continuity Analysis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-8b4baf804e461d9b72633f0de59a0cac.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-f2f602f58a1feb3413044be4aec0a068.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Papal Continuity Analysis</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link active" href="./index.html" aria-current="page"> 
<span class="menu-text">Analysis</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://bleonardi.shinyapps.io/papal-rag-chat/"> 
<span class="menu-text">Chat with the Corpus</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#abstract" id="toc-abstract" class="nav-link active" data-scroll-target="#abstract">Abstract</a></li>
  <li><a href="#i.-introduction" id="toc-i.-introduction" class="nav-link" data-scroll-target="#i.-introduction">I. Introduction</a></li>
  <li><a href="#ii.-data" id="toc-ii.-data" class="nav-link" data-scroll-target="#ii.-data">II. Data</a>
  <ul class="collapse">
  <li><a href="#corpora" id="toc-corpora" class="nav-link" data-scroll-target="#corpora">2.1 Corpora</a></li>
  <li><a href="#rupture-events" id="toc-rupture-events" class="nav-link" data-scroll-target="#rupture-events">2.2 Rupture Events</a></li>
  </ul></li>
  <li><a href="#iii.-methods" id="toc-iii.-methods" class="nav-link" data-scroll-target="#iii.-methods">III. Methods</a>
  <ul class="collapse">
  <li><a href="#textual-features" id="toc-textual-features" class="nav-link" data-scroll-target="#textual-features">3.1 Textual Features</a></li>
  <li><a href="#interrupted-time-series" id="toc-interrupted-time-series" class="nav-link" data-scroll-target="#interrupted-time-series">3.2 Interrupted Time Series</a></li>
  <li><a href="#difference-in-differences" id="toc-difference-in-differences" class="nav-link" data-scroll-target="#difference-in-differences">3.3 Difference-in-Differences</a></li>
  <li><a href="#on-regression-discontinuity" id="toc-on-regression-discontinuity" class="nav-link" data-scroll-target="#on-regression-discontinuity">3.4 On Regression Discontinuity</a></li>
  </ul></li>
  <li><a href="#iv.-results" id="toc-iv.-results" class="nav-link" data-scroll-target="#iv.-results">IV. Results</a>
  <ul class="collapse">
  <li><a href="#stylistic-change-at-vatican-ii" id="toc-stylistic-change-at-vatican-ii" class="nav-link" data-scroll-target="#stylistic-change-at-vatican-ii">4.1 Stylistic Change at Vatican II</a></li>
  <li><a href="#theological-vocabulary" id="toc-theological-vocabulary" class="nav-link" data-scroll-target="#theological-vocabulary">4.2 Theological Vocabulary</a></li>
  <li><a href="#difference-in-differences-catholic-vs.-lds" id="toc-difference-in-differences-catholic-vs.-lds" class="nav-link" data-scroll-target="#difference-in-differences-catholic-vs.-lds">4.3 Difference-in-Differences: Catholic vs.&nbsp;LDS</a></li>
  <li><a href="#comparison-across-traditions" id="toc-comparison-across-traditions" class="nav-link" data-scroll-target="#comparison-across-traditions">4.4 Comparison Across Traditions</a></li>
  <li><a href="#within-catholic-vatican-ii-vs.-earlier-transitions" id="toc-within-catholic-vatican-ii-vs.-earlier-transitions" class="nav-link" data-scroll-target="#within-catholic-vatican-ii-vs.-earlier-transitions">4.5 Within-Catholic: Vatican II vs.&nbsp;Earlier Transitions</a></li>
  <li><a href="#usccb-pastoral-letters-downstream-coherence" id="toc-usccb-pastoral-letters-downstream-coherence" class="nav-link" data-scroll-target="#usccb-pastoral-letters-downstream-coherence">4.6 USCCB Pastoral Letters: Downstream Coherence</a></li>
  </ul></li>
  <li><a href="#v.-discussion" id="toc-v.-discussion" class="nav-link" data-scroll-target="#v.-discussion">V. Discussion</a></li>
  <li><a href="#vi.-conclusion" id="toc-vi.-conclusion" class="nav-link" data-scroll-target="#vi.-conclusion">VI. Conclusion</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Continuity or Rupture? A Text-as-Data Analysis of Vatican II and Comparative Doctrinal Change</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Benedict Leonardi </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">July 8, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="abstract" class="level2">
<h2 class="anchored" data-anchor-id="abstract">Abstract</h2>
<p>A dominant narrative in post-conciliar Catholic discourse holds that the Second Vatican Council (1962–1965) produced a fundamental rupture with prior tradition — a discontinuity in doctrine, style, and theological orientation. This paper tests that claim empirically using a large corpus of primary documents. Applying interrupted time series (ITS) and difference-in-differences (DiD) models to over 1,900 documents across five Christian traditions (Catholic encyclicals 1878–2024, LDS general conference reports 1880–1980, SBC resolutions 1845–2026, Anglican Lambeth conference statements 1867–1998, and Eastern Orthodox patriarchal documents 1902–2026), we find that Vatican II coincides with a significant stylistic simplification — shorter sentences, lower reading complexity — but no detectable discontinuity in theological vocabulary emphasis. More strikingly, Catholic documents become <em>more</em> textually consistent with each other after 1965, not less. The rupture narrative finds no support in the textual record.</p>
<hr>
<p><strong>Keywords:</strong> Vatican II, Hermeneutic of Continuity, Text-as-Data, Interrupted Time Series, Papal Encyclicals, Comparative Religion</p>
<hr>
</section>
<section id="i.-introduction" class="level2">
<h2 class="anchored" data-anchor-id="i.-introduction">I. Introduction</h2>
<p>The question of whether the Second Vatican Council represents a break or a development within the Catholic tradition is among the most contested debates in contemporary Catholic intellectual life. Proponents of the “rupture” interpretation — associated with figures like Archbishop Marcel Lefebvre and, in a different register, some progressive theologians — argue that Vatican II produced a new Church, discontinuous in key respects with its predecessor. The “hermeneutic of continuity,” articulated most prominently by Benedict XVI, holds instead that the council’s documents, properly interpreted, represent organic development rather than rupture.</p>
<p>This paper does not take a side in that theological dispute. Instead, it asks an antecedent empirical question: <em>what does the textual record actually show?</em> If Vatican II produced a rupture, we would expect to observe, in the documents themselves, a measurable discontinuity at 1965 — a shift in vocabulary, style, theological emphasis, or intertextual coherence that exceeds any pre-existing trend. If the continuity thesis is correct, such discontinuities should be modest or absent, and the corpus of post-conciliar encyclicals should remain recognizably connected to its predecessors.</p>
<p>We further situate the Catholic case comparatively. Other Christian traditions underwent their own rupture events over the same period: the Anglican Communion’s ordination debates (Lambeth 1976–1978), the Southern Baptist Conservative Resurgence (1979), and shifts in LDS institutional discourse. If Vatican II is unusually disruptive, Catholic documents should show larger discontinuities than peer traditions at their own rupture events.</p>
</section>
<section id="ii.-data" class="level2">
<h2 class="anchored" data-anchor-id="ii.-data">II. Data</h2>
<section id="corpora" class="level3">
<h3 class="anchored" data-anchor-id="corpora">2.1 Corpora</h3>
<div id="7f0fd7a8" class="cell" data-execution_count="2">
<div class="cell-output cell-output-display">
<style type="text/css">
</style>

<table id="T_f03a3" class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th id="T_f03a3_level0_col0" class="col_heading level0 col0" data-quarto-table-cell-role="th">Tradition</th>
<th id="T_f03a3_level0_col1" class="col_heading level0 col1" data-quarto-table-cell-role="th">Documents</th>
<th id="T_f03a3_level0_col2" class="col_heading level0 col2" data-quarto-table-cell-role="th">First Year</th>
<th id="T_f03a3_level0_col3" class="col_heading level0 col3" data-quarto-table-cell-role="th">Last Year</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td id="T_f03a3_row0_col0" class="data row0 col0">Anglican</td>
<td id="T_f03a3_row0_col1" class="data row0 col1">14</td>
<td id="T_f03a3_row0_col2" class="data row0 col2">1867</td>
<td id="T_f03a3_row0_col3" class="data row0 col3">2022</td>
</tr>
<tr class="even">
<td id="T_f03a3_row1_col0" class="data row1 col0">Catholic</td>
<td id="T_f03a3_row1_col1" class="data row1 col1">222</td>
<td id="T_f03a3_row1_col2" class="data row1 col2">1878</td>
<td id="T_f03a3_row1_col3" class="data row1 col3">2024</td>
</tr>
<tr class="odd">
<td id="T_f03a3_row2_col0" class="data row2 col0">Lds</td>
<td id="T_f03a3_row2_col1" class="data row2 col1">505</td>
<td id="T_f03a3_row2_col2" class="data row2 col2">1880</td>
<td id="T_f03a3_row2_col3" class="data row2 col3">1975</td>
</tr>
<tr class="even">
<td id="T_f03a3_row3_col0" class="data row3 col0">Orthodox</td>
<td id="T_f03a3_row3_col1" class="data row3 col1">27</td>
<td id="T_f03a3_row3_col2" class="data row3 col2">1902</td>
<td id="T_f03a3_row3_col3" class="data row3 col3">2026</td>
</tr>
<tr class="odd">
<td id="T_f03a3_row4_col0" class="data row4 col0">Sbc</td>
<td id="T_f03a3_row4_col1" class="data row4 col1">1132</td>
<td id="T_f03a3_row4_col2" class="data row4 col2">1845</td>
<td id="T_f03a3_row4_col3" class="data row4 col3">2026</td>
</tr>
<tr class="even">
<td id="T_f03a3_row5_col0" class="data row5 col0">Usccb</td>
<td id="T_f03a3_row5_col1" class="data row5 col1">16</td>
<td id="T_f03a3_row5_col2" class="data row5 col2">1919</td>
<td id="T_f03a3_row5_col3" class="data row5 col3">2026</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>Catholic</strong> encyclicals were scraped from the Vatican’s official website (vatican.va), supplemented with English translations from papalencyclicals.net for documents unavailable in English on the Vatican site. The corpus spans Leo XIII through Francis (1878–2024), covering 222 encyclicals across 13 pontificates.</p>
<p><strong>LDS</strong> general conference reports were sourced from the Internet Archive (pre-1971 session transcripts) and churchofjesuschrist.org (individual talks, 1971–1980). Documents were aggregated to the annual level (one document per year) to match the session-level granularity of the Catholic corpus.</p>
<p><strong>SBC</strong> resolutions were scraped from sbc.net, yielding 1,195 resolutions from 1845 to 2026.</p>
<p><strong>Anglican</strong> Lambeth Conference statements were extracted from PDFs at anglicancommunion.org, covering 13 decennial conferences from 1867 to 1998.</p>
<p><strong>Orthodox</strong> documents represent a curated set of 27 patriarchal encyclicals and major council statements (1902–2026) drawn from published translations of Ecumenical Patriarchate documents and ec-patr.org.</p>
</section>
<section id="rupture-events" class="level3">
<h3 class="anchored" data-anchor-id="rupture-events">2.2 Rupture Events</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Tradition</th>
<th>Rupture Event</th>
<th>Year</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Catholic</td>
<td>Vatican II closes</td>
<td>1965</td>
</tr>
<tr class="even">
<td>Anglican</td>
<td>Lambeth ordination debates</td>
<td>1976</td>
</tr>
<tr class="odd">
<td>SBC</td>
<td>Conservative Resurgence begins</td>
<td>1979</td>
</tr>
<tr class="even">
<td>LDS</td>
<td>No strong rupture candidate</td>
<td>—</td>
</tr>
<tr class="odd">
<td>Orthodox</td>
<td>Paul VI–Athenagoras declaration</td>
<td>1965</td>
</tr>
</tbody>
</table>
<p>LDS serves as the primary control group in the DiD specification, as it exhibits no comparable institutional rupture event over the study period.</p>
</section>
</section>
<section id="iii.-methods" class="level2">
<h2 class="anchored" data-anchor-id="iii.-methods">III. Methods</h2>
<section id="textual-features" class="level3">
<h3 class="anchored" data-anchor-id="textual-features">3.1 Textual Features</h3>
<p>For each document we compute:</p>
<ul>
<li><strong>Readability:</strong> Flesch-Kincaid grade level, Flesch reading ease, average sentence length</li>
<li><strong>Lexical diversity:</strong> Type-token ratio (TTR)</li>
<li><strong>Register:</strong> Hedging word rate, first-person plural rate</li>
<li><strong>Theological vocabulary:</strong> Rate of terms per 1,000 words in four clusters — <em>juridical</em> (canon, decree, obedience, authority…), <em>pastoral</em> (shepherd, mercy, compassion, encounter…), <em>ecumenical</em> (unity, dialogue, reconciliation…), <em>modern world</em> (contemporary, human dignity, rights, progress…)</li>
<li><strong>Intertextual continuity:</strong> Cosine similarity between a document’s TF-IDF vector and that of its chronological predecessor within the same tradition</li>
</ul>
</section>
<section id="interrupted-time-series" class="level3">
<h3 class="anchored" data-anchor-id="interrupted-time-series">3.2 Interrupted Time Series</h3>
<p>For each tradition and outcome, we estimate:</p>
<p><span class="math display">\[Y_t = \beta_0 + \beta_1 \cdot \text{time}_t + \beta_2 \cdot \text{post}_t + \beta_3 \cdot (\text{time}_t \times \text{post}_t) + \varepsilon_t\]</span></p>
<p>where <span class="math inline">\(\text{post}_t = \mathbf{1}[t \geq \text{cutoff}]\)</span> and <span class="math inline">\(\text{time}_t\)</span> is years centered at the cutoff. <span class="math inline">\(\beta_2\)</span> estimates the <strong>level change</strong> at the rupture event; <span class="math inline">\(\beta_3\)</span> the <strong>slope change</strong>. All models use HC3 heteroskedasticity-robust standard errors.</p>
</section>
<section id="difference-in-differences" class="level3">
<h3 class="anchored" data-anchor-id="difference-in-differences">3.3 Difference-in-Differences</h3>
<p>To partial out secular trends common to all traditions (general prose simplification over the 20th century), we estimate a DiD using Catholic as treatment and annual-aggregated LDS as control:</p>
<p><span class="math display">\[Y_{it} = \alpha + \gamma \cdot \text{treated}_i + \delta \cdot \text{post}_t + \tau \cdot (\text{treated}_i \times \text{post}_t) + \lambda \cdot \text{time}_t + \mu \cdot (\text{time}_t \times \text{treated}_i) + \varepsilon_{it}\]</span></p>
<p><span class="math inline">\(\tau\)</span> is the DiD estimator — the Catholic-specific change at 1965 net of any LDS trend. HC3 robust SEs throughout.</p>
</section>
<section id="on-regression-discontinuity" class="level3">
<h3 class="anchored" data-anchor-id="on-regression-discontinuity">3.4 On Regression Discontinuity</h3>
<p>RD estimation at the 1965 cutoff was considered but not adopted as a primary specification. RD requires that units cannot precisely manipulate their position around the running-variable threshold. Papal documents, however, are strategically timed — Paul VI demonstrably delayed issuing <em>Humanae Vitae</em> until after the council closed, and several encyclicals were explicitly framed as council implementations. This creates plausible sorting around the 1965 threshold that violates the RD continuity assumption. The ITS specification is more appropriate for a long institutional series and subsumes the RD identifying variation.</p>
</section>
</section>
<section id="iv.-results" class="level2">
<h2 class="anchored" data-anchor-id="iv.-results">IV. Results</h2>
<section id="stylistic-change-at-vatican-ii" class="level3">
<h3 class="anchored" data-anchor-id="stylistic-change-at-vatican-ii">4.1 Stylistic Change at Vatican II</h3>
<p>The ITS estimates confirm a significant level change in surface stylistic features at 1965:</p>
<div id="6475131f" class="cell" data-execution_count="3">
<div class="cell-output cell-output-display">
<style type="text/css">
</style>

<table id="T_115d0" class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th id="T_115d0_level0_col0" class="col_heading level0 col0" data-quarto-table-cell-role="th">Outcome</th>
<th id="T_115d0_level0_col1" class="col_heading level0 col1" data-quarto-table-cell-role="th">N</th>
<th id="T_115d0_level0_col2" class="col_heading level0 col2" data-quarto-table-cell-role="th">Level Δ</th>
<th id="T_115d0_level0_col3" class="col_heading level0 col3" data-quarto-table-cell-role="th">SE</th>
<th id="T_115d0_level0_col4" class="col_heading level0 col4" data-quarto-table-cell-role="th">p</th>
<th id="T_115d0_level0_col5" class="col_heading level0 col5" data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td id="T_115d0_row0_col0" class="data row0 col0">Fk Grade</td>
<td id="T_115d0_row0_col1" class="data row0 col1">222</td>
<td id="T_115d0_row0_col2" class="data row0 col2">-2.128200</td>
<td id="T_115d0_row0_col3" class="data row0 col3">0.867000</td>
<td id="T_115d0_row0_col4" class="data row0 col4">0.014100</td>
<td id="T_115d0_row0_col5" class="data row0 col5">**</td>
</tr>
<tr class="even">
<td id="T_115d0_row1_col0" class="data row1 col0">Flesch Ease</td>
<td id="T_115d0_row1_col1" class="data row1 col1">222</td>
<td id="T_115d0_row1_col2" class="data row1 col2">5.319500</td>
<td id="T_115d0_row1_col3" class="data row1 col3">2.969200</td>
<td id="T_115d0_row1_col4" class="data row1 col4">0.073200</td>
<td id="T_115d0_row1_col5" class="data row1 col5">†</td>
</tr>
<tr class="odd">
<td id="T_115d0_row2_col0" class="data row2 col0">Type Token Ratio</td>
<td id="T_115d0_row2_col1" class="data row2 col1">222</td>
<td id="T_115d0_row2_col2" class="data row2 col2">-0.058500</td>
<td id="T_115d0_row2_col3" class="data row2 col3">0.035900</td>
<td id="T_115d0_row2_col4" class="data row2 col4">0.103300</td>
<td id="T_115d0_row2_col5" class="data row2 col5"></td>
</tr>
<tr class="even">
<td id="T_115d0_row3_col0" class="data row3 col0">Avg Sentence Length</td>
<td id="T_115d0_row3_col1" class="data row3 col1">222</td>
<td id="T_115d0_row3_col2" class="data row3 col2">-5.583500</td>
<td id="T_115d0_row3_col3" class="data row3 col3">2.143100</td>
<td id="T_115d0_row3_col4" class="data row3 col4">0.009200</td>
<td id="T_115d0_row3_col5" class="data row3 col5">**</td>
</tr>
<tr class="odd">
<td id="T_115d0_row4_col0" class="data row4 col0">Hedge Rate</td>
<td id="T_115d0_row4_col1" class="data row4 col1">222</td>
<td id="T_115d0_row4_col2" class="data row4 col2">-0.001200</td>
<td id="T_115d0_row4_col3" class="data row4 col3">0.001000</td>
<td id="T_115d0_row4_col4" class="data row4 col4">0.222000</td>
<td id="T_115d0_row4_col5" class="data row4 col5"></td>
</tr>
<tr class="even">
<td id="T_115d0_row5_col0" class="data row5 col0">Fp Plural Rate</td>
<td id="T_115d0_row5_col1" class="data row5 col1">222</td>
<td id="T_115d0_row5_col2" class="data row5 col2">-0.008000</td>
<td id="T_115d0_row5_col3" class="data row5 col3">0.004000</td>
<td id="T_115d0_row5_col4" class="data row5 col4">0.046500</td>
<td id="T_115d0_row5_col5" class="data row5 col5">**</td>
</tr>
<tr class="odd">
<td id="T_115d0_row6_col0" class="data row6 col0">Theol Juridical Rate</td>
<td id="T_115d0_row6_col1" class="data row6 col1">222</td>
<td id="T_115d0_row6_col2" class="data row6 col2">0.001000</td>
<td id="T_115d0_row6_col3" class="data row6 col3">0.001000</td>
<td id="T_115d0_row6_col4" class="data row6 col4">0.346600</td>
<td id="T_115d0_row6_col5" class="data row6 col5"></td>
</tr>
<tr class="even">
<td id="T_115d0_row7_col0" class="data row7 col0">Theol Pastoral Rate</td>
<td id="T_115d0_row7_col1" class="data row7 col1">222</td>
<td id="T_115d0_row7_col2" class="data row7 col2">0.000500</td>
<td id="T_115d0_row7_col3" class="data row7 col3">0.000900</td>
<td id="T_115d0_row7_col4" class="data row7 col4">0.580300</td>
<td id="T_115d0_row7_col5" class="data row7 col5"></td>
</tr>
<tr class="odd">
<td id="T_115d0_row8_col0" class="data row8 col0">Theol Ecumenical Rate</td>
<td id="T_115d0_row8_col1" class="data row8 col1">222</td>
<td id="T_115d0_row8_col2" class="data row8 col2">-0.001000</td>
<td id="T_115d0_row8_col3" class="data row8 col3">0.000800</td>
<td id="T_115d0_row8_col4" class="data row8 col4">0.225800</td>
<td id="T_115d0_row8_col5" class="data row8 col5"></td>
</tr>
<tr class="even">
<td id="T_115d0_row9_col0" class="data row9 col0">Theol Modern World Rate</td>
<td id="T_115d0_row9_col1" class="data row9 col1">222</td>
<td id="T_115d0_row9_col2" class="data row9 col2">0.001500</td>
<td id="T_115d0_row9_col3" class="data row9 col3">0.001400</td>
<td id="T_115d0_row9_col4" class="data row9 col4">0.269700</td>
<td id="T_115d0_row9_col5" class="data row9 col5"></td>
</tr>
<tr class="odd">
<td id="T_115d0_row10_col0" class="data row10 col0">Cosine Sim To Prev</td>
<td id="T_115d0_row10_col1" class="data row10 col1">221</td>
<td id="T_115d0_row10_col2" class="data row10 col2">0.095300</td>
<td id="T_115d0_row10_col3" class="data row10 col3">0.039000</td>
<td id="T_115d0_row10_col4" class="data row10 col4">0.014500</td>
<td id="T_115d0_row10_col5" class="data row10 col5">**</td>
</tr>
<tr class="even">
<td id="T_115d0_row11_col0" class="data row11 col0">Fk Grade</td>
<td id="T_115d0_row11_col1" class="data row11 col1">222</td>
<td id="T_115d0_row11_col2" class="data row11 col2">-2.128200</td>
<td id="T_115d0_row11_col3" class="data row11 col3">0.867000</td>
<td id="T_115d0_row11_col4" class="data row11 col4">0.014100</td>
<td id="T_115d0_row11_col5" class="data row11 col5">**</td>
</tr>
<tr class="odd">
<td id="T_115d0_row12_col0" class="data row12 col0">Avg Sentence Length</td>
<td id="T_115d0_row12_col1" class="data row12 col1">222</td>
<td id="T_115d0_row12_col2" class="data row12 col2">-5.583500</td>
<td id="T_115d0_row12_col3" class="data row12 col3">2.143100</td>
<td id="T_115d0_row12_col4" class="data row12 col4">0.009200</td>
<td id="T_115d0_row12_col5" class="data row12 col5">**</td>
</tr>
<tr class="even">
<td id="T_115d0_row13_col0" class="data row13 col0">Type Token Ratio</td>
<td id="T_115d0_row13_col1" class="data row13 col1">222</td>
<td id="T_115d0_row13_col2" class="data row13 col2">-0.058500</td>
<td id="T_115d0_row13_col3" class="data row13 col3">0.035900</td>
<td id="T_115d0_row13_col4" class="data row13 col4">0.103300</td>
<td id="T_115d0_row13_col5" class="data row13 col5"></td>
</tr>
<tr class="odd">
<td id="T_115d0_row14_col0" class="data row14 col0">Cosine Sim To Prev</td>
<td id="T_115d0_row14_col1" class="data row14 col1">221</td>
<td id="T_115d0_row14_col2" class="data row14 col2">0.095300</td>
<td id="T_115d0_row14_col3" class="data row14 col3">0.039000</td>
<td id="T_115d0_row14_col4" class="data row14 col4">0.014500</td>
<td id="T_115d0_row14_col5" class="data row14 col5">**</td>
</tr>
<tr class="even">
<td id="T_115d0_row15_col0" class="data row15 col0">Theol Pastoral Rate</td>
<td id="T_115d0_row15_col1" class="data row15 col1">222</td>
<td id="T_115d0_row15_col2" class="data row15 col2">0.000500</td>
<td id="T_115d0_row15_col3" class="data row15 col3">0.000900</td>
<td id="T_115d0_row15_col4" class="data row15 col4">0.580300</td>
<td id="T_115d0_row15_col5" class="data row15 col5"></td>
</tr>
<tr class="odd">
<td id="T_115d0_row16_col0" class="data row16 col0">Theol Juridical Rate</td>
<td id="T_115d0_row16_col1" class="data row16 col1">222</td>
<td id="T_115d0_row16_col2" class="data row16 col2">0.001000</td>
<td id="T_115d0_row16_col3" class="data row16 col3">0.001000</td>
<td id="T_115d0_row16_col4" class="data row16 col4">0.346600</td>
<td id="T_115d0_row16_col5" class="data row16 col5"></td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Sentence length drops by 5.6 words at 1965 (p = 0.009), Flesch-Kincaid grade falls by 2.1 points (p = 0.014), and first-person plural usage declines (p = 0.047). None of the four theological vocabulary clusters show significant level changes. The pastoral, ecumenical, juridical, and modern-world term rates are statistically flat across the 1965 boundary.</p>
<p>Most striking is the cosine similarity result: documents become <em>more</em> similar to their predecessors after Vatican II (level Δ = +0.095, p = 0.015). The rupture narrative would predict the opposite.</p>
<div id="cell-fig-cosine-catholic" class="cell" data-execution_count="4">
<div class="cell-output cell-output-display">
<div id="fig-cosine-catholic" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-cosine-catholic-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-cosine-catholic-output-1.png" width="1485" height="660" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cosine-catholic-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Catholic encyclicals show <em>increased</em> intertextual continuity after Vatican II. Rolling mean (5 documents) overlaid on raw values. Dashed line = 1965.
</figcaption>
</figure>
</div>
</div>
</div>
<div id="cell-fig-sentence-length" class="cell" data-execution_count="5">
<div class="cell-output cell-output-display">
<div id="fig-sentence-length" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-sentence-length-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-sentence-length-output-1.png" width="1486" height="660" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-sentence-length-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Average sentence length in Catholic encyclicals falls at Vatican II. Pre- and post-1965 OLS trend lines shown.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="theological-vocabulary" class="level3">
<h3 class="anchored" data-anchor-id="theological-vocabulary">4.2 Theological Vocabulary</h3>
<div id="cell-fig-vocab" class="cell" data-execution_count="6">
<div class="cell-output cell-output-display">
<div id="fig-vocab" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-vocab-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-vocab-output-1.png" width="1786" height="1036" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-vocab-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Theological vocabulary cluster rates per 1,000 words in Catholic encyclicals, 1878–2024. No cluster shows a discontinuous shift at Vatican II.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="difference-in-differences-catholic-vs.-lds" class="level3">
<h3 class="anchored" data-anchor-id="difference-in-differences-catholic-vs.-lds">4.3 Difference-in-Differences: Catholic vs.&nbsp;LDS</h3>
<p>To isolate the Vatican II effect from secular prose trends, Table 2 reports DiD estimates using annual LDS conference totals as a control. The parallel trends assumption holds to the extent that both traditions experienced similar underlying pressures toward simpler prose in the mid-20th century — a reasonable prior given that both were producing primarily spoken/homiletic text by the postwar period.</p>
<div id="c4d4ef26" class="cell" data-execution_count="7">
<div class="cell-output cell-output-display">
<style type="text/css">
</style>

<table id="T_01e80" class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th id="T_01e80_level0_col0" class="col_heading level0 col0" data-quarto-table-cell-role="th">Outcome</th>
<th id="T_01e80_level0_col1" class="col_heading level0 col1" data-quarto-table-cell-role="th">DiD Coef</th>
<th id="T_01e80_level0_col2" class="col_heading level0 col2" data-quarto-table-cell-role="th">SE</th>
<th id="T_01e80_level0_col3" class="col_heading level0 col3" data-quarto-table-cell-role="th">p</th>
<th id="T_01e80_level0_col4" class="col_heading level0 col4" data-quarto-table-cell-role="th">R²</th>
<th id="T_01e80_level0_col5" class="col_heading level0 col5" data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td id="T_01e80_row0_col0" class="data row0 col0">Fk Grade</td>
<td id="T_01e80_row0_col1" class="data row0 col1">-2.259400</td>
<td id="T_01e80_row0_col2" class="data row0 col2">0.759600</td>
<td id="T_01e80_row0_col3" class="data row0 col3">0.002900</td>
<td id="T_01e80_row0_col4" class="data row0 col4">0.446500</td>
<td id="T_01e80_row0_col5" class="data row0 col5">**</td>
</tr>
<tr class="even">
<td id="T_01e80_row1_col0" class="data row1 col0">Flesch Ease</td>
<td id="T_01e80_row1_col1" class="data row1 col1">3.313700</td>
<td id="T_01e80_row1_col2" class="data row1 col2">2.485800</td>
<td id="T_01e80_row1_col3" class="data row1 col3">0.182500</td>
<td id="T_01e80_row1_col4" class="data row1 col4">0.581600</td>
<td id="T_01e80_row1_col5" class="data row1 col5"></td>
</tr>
<tr class="odd">
<td id="T_01e80_row2_col0" class="data row2 col0">Type Token Ratio</td>
<td id="T_01e80_row2_col1" class="data row2 col1">-0.089400</td>
<td id="T_01e80_row2_col2" class="data row2 col2">0.026500</td>
<td id="T_01e80_row2_col3" class="data row2 col3">0.000700</td>
<td id="T_01e80_row2_col4" class="data row2 col4">0.669600</td>
<td id="T_01e80_row2_col5" class="data row2 col5">**</td>
</tr>
<tr class="even">
<td id="T_01e80_row3_col0" class="data row3 col0">Avg Sentence Length</td>
<td id="T_01e80_row3_col1" class="data row3 col1">-7.233700</td>
<td id="T_01e80_row3_col2" class="data row3 col2">1.880200</td>
<td id="T_01e80_row3_col3" class="data row3 col3">0.000100</td>
<td id="T_01e80_row3_col4" class="data row3 col4">0.298100</td>
<td id="T_01e80_row3_col5" class="data row3 col5">**</td>
</tr>
<tr class="odd">
<td id="T_01e80_row4_col0" class="data row4 col0">Hedge Rate</td>
<td id="T_01e80_row4_col1" class="data row4 col1">-0.001900</td>
<td id="T_01e80_row4_col2" class="data row4 col2">0.000700</td>
<td id="T_01e80_row4_col3" class="data row4 col3">0.003600</td>
<td id="T_01e80_row4_col4" class="data row4 col4">0.068000</td>
<td id="T_01e80_row4_col5" class="data row4 col5">**</td>
</tr>
<tr class="even">
<td id="T_01e80_row5_col0" class="data row5 col0">Fp Plural Rate</td>
<td id="T_01e80_row5_col1" class="data row5 col1">-0.006300</td>
<td id="T_01e80_row5_col2" class="data row5 col2">0.002600</td>
<td id="T_01e80_row5_col3" class="data row5 col3">0.016100</td>
<td id="T_01e80_row5_col4" class="data row5 col4">0.079600</td>
<td id="T_01e80_row5_col5" class="data row5 col5">**</td>
</tr>
<tr class="odd">
<td id="T_01e80_row6_col0" class="data row6 col0">Theol Juridical Rate</td>
<td id="T_01e80_row6_col1" class="data row6 col1">0.000700</td>
<td id="T_01e80_row6_col2" class="data row6 col2">0.000700</td>
<td id="T_01e80_row6_col3" class="data row6 col3">0.354400</td>
<td id="T_01e80_row6_col4" class="data row6 col4">0.174100</td>
<td id="T_01e80_row6_col5" class="data row6 col5"></td>
</tr>
<tr class="even">
<td id="T_01e80_row7_col0" class="data row7 col0">Theol Pastoral Rate</td>
<td id="T_01e80_row7_col1" class="data row7 col1">0.000400</td>
<td id="T_01e80_row7_col2" class="data row7 col2">0.000600</td>
<td id="T_01e80_row7_col3" class="data row7 col3">0.466700</td>
<td id="T_01e80_row7_col4" class="data row7 col4">0.223400</td>
<td id="T_01e80_row7_col5" class="data row7 col5"></td>
</tr>
<tr class="odd">
<td id="T_01e80_row8_col0" class="data row8 col0">Theol Ecumenical Rate</td>
<td id="T_01e80_row8_col1" class="data row8 col1">-0.000600</td>
<td id="T_01e80_row8_col2" class="data row8 col2">0.000900</td>
<td id="T_01e80_row8_col3" class="data row8 col3">0.497100</td>
<td id="T_01e80_row8_col4" class="data row8 col4">0.114000</td>
<td id="T_01e80_row8_col5" class="data row8 col5"></td>
</tr>
<tr class="even">
<td id="T_01e80_row9_col0" class="data row9 col0">Theol Modern World Rate</td>
<td id="T_01e80_row9_col1" class="data row9 col1">0.001400</td>
<td id="T_01e80_row9_col2" class="data row9 col2">0.000900</td>
<td id="T_01e80_row9_col3" class="data row9 col3">0.123700</td>
<td id="T_01e80_row9_col4" class="data row9 col4">0.205200</td>
<td id="T_01e80_row9_col5" class="data row9 col5"></td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The results confirm the ITS pattern. Catholic underwent a significant <em>stylistic</em> shift at 1965 relative to LDS — simpler sentences, lower grade level, reduced lexical diversity — but none of the theological vocabulary clusters shift significantly. The DiD R² for cosine similarity is excluded here because document-size mismatch between the two corpora (even after LDS aggregation) makes the cosine comparison unreliable for cross-tradition DiD; cosine results are interpreted within-tradition only.</p>
</section>
<section id="comparison-across-traditions" class="level3">
<h3 class="anchored" data-anchor-id="comparison-across-traditions">4.4 Comparison Across Traditions</h3>
<div id="cell-fig-cross-tradition" class="cell" data-execution_count="8">
<div class="cell-output cell-output-display">
<div id="fig-cross-tradition" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-cross-tradition-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-cross-tradition-output-1.png" width="1784" height="660" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cross-tradition-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: ITS level-change estimates at each tradition’s rupture event. Catholic’s shifts are modest and negative (simpler prose). SBC’s Conservative Resurgence (1979) produces large positive shifts in both FK grade (+12.2) and sentence length (+28.7 words) — resolutions became longer and more legalistic. Anglican and Orthodox estimates are imprecise (small n).
</figcaption>
</figure>
</div>
</div>
</div>
<p>The SBC Conservative Resurgence (1979) produces a large, precisely estimated <em>increase</em> in Flesch-Kincaid grade (+12.2, p = 0.003) — resolutions became substantially more formal and legalistic after the conservative takeover. Catholic’s Vatican II shift is negative and smaller in magnitude. Anglican and Orthodox estimates are imprecise given small n.</p>
</section>
<section id="within-catholic-vatican-ii-vs.-earlier-transitions" class="level3">
<h3 class="anchored" data-anchor-id="within-catholic-vatican-ii-vs.-earlier-transitions">4.5 Within-Catholic: Vatican II vs.&nbsp;Earlier Transitions</h3>
<p>As a placebo check, we re-run the ITS at 1903 (the Leo XIII–Pius X transition, often cited as a doctrinal watershed via <em>Lamentabili</em> and <em>Pascendi</em>):</p>
<div id="cc04d85a" class="cell" data-execution_count="9">
<div class="cell-output cell-output-display">
<style type="text/css">
</style>

<table id="T_a0c6d" class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th id="T_a0c6d_level0_col0" class="col_heading level0 col0" data-quarto-table-cell-role="th">Outcome</th>
<th id="T_a0c6d_level0_col1" class="col_heading level0 col1" data-quarto-table-cell-role="th">Level Δ</th>
<th id="T_a0c6d_level0_col2" class="col_heading level0 col2" data-quarto-table-cell-role="th">SE</th>
<th id="T_a0c6d_level0_col3" class="col_heading level0 col3" data-quarto-table-cell-role="th">p</th>
<th id="T_a0c6d_level0_col4" class="col_heading level0 col4" data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td id="T_a0c6d_row0_col0" class="data row0 col0">Fk Grade</td>
<td id="T_a0c6d_row0_col1" class="data row0 col1">4.008500</td>
<td id="T_a0c6d_row0_col2" class="data row0 col2">0.665600</td>
<td id="T_a0c6d_row0_col3" class="data row0 col3">0.000000</td>
<td id="T_a0c6d_row0_col4" class="data row0 col4">**</td>
</tr>
<tr class="even">
<td id="T_a0c6d_row1_col0" class="data row1 col0">Flesch Ease</td>
<td id="T_a0c6d_row1_col1" class="data row1 col1">-7.469800</td>
<td id="T_a0c6d_row1_col2" class="data row1 col2">2.124800</td>
<td id="T_a0c6d_row1_col3" class="data row1 col3">0.000400</td>
<td id="T_a0c6d_row1_col4" class="data row1 col4">**</td>
</tr>
<tr class="odd">
<td id="T_a0c6d_row2_col0" class="data row2 col0">Type Token Ratio</td>
<td id="T_a0c6d_row2_col1" class="data row2 col1">-0.048100</td>
<td id="T_a0c6d_row2_col2" class="data row2 col2">0.023300</td>
<td id="T_a0c6d_row2_col3" class="data row2 col3">0.039500</td>
<td id="T_a0c6d_row2_col4" class="data row2 col4">**</td>
</tr>
<tr class="even">
<td id="T_a0c6d_row3_col0" class="data row3 col0">Avg Sentence Length</td>
<td id="T_a0c6d_row3_col1" class="data row3 col1">11.945900</td>
<td id="T_a0c6d_row3_col2" class="data row3 col2">1.721400</td>
<td id="T_a0c6d_row3_col3" class="data row3 col3">0.000000</td>
<td id="T_a0c6d_row3_col4" class="data row3 col4">**</td>
</tr>
<tr class="odd">
<td id="T_a0c6d_row4_col0" class="data row4 col0">Hedge Rate</td>
<td id="T_a0c6d_row4_col1" class="data row4 col1">0.001300</td>
<td id="T_a0c6d_row4_col2" class="data row4 col2">0.000500</td>
<td id="T_a0c6d_row4_col3" class="data row4 col3">0.010500</td>
<td id="T_a0c6d_row4_col4" class="data row4 col4">**</td>
</tr>
<tr class="even">
<td id="T_a0c6d_row5_col0" class="data row5 col0">Fp Plural Rate</td>
<td id="T_a0c6d_row5_col1" class="data row5 col1">-0.005500</td>
<td id="T_a0c6d_row5_col2" class="data row5 col2">0.002500</td>
<td id="T_a0c6d_row5_col3" class="data row5 col3">0.030400</td>
<td id="T_a0c6d_row5_col4" class="data row5 col4">**</td>
</tr>
<tr class="odd">
<td id="T_a0c6d_row6_col0" class="data row6 col0">Theol Juridical Rate</td>
<td id="T_a0c6d_row6_col1" class="data row6 col1">0.000900</td>
<td id="T_a0c6d_row6_col2" class="data row6 col2">0.001000</td>
<td id="T_a0c6d_row6_col3" class="data row6 col3">0.340400</td>
<td id="T_a0c6d_row6_col4" class="data row6 col4"></td>
</tr>
<tr class="even">
<td id="T_a0c6d_row7_col0" class="data row7 col0">Theol Pastoral Rate</td>
<td id="T_a0c6d_row7_col1" class="data row7 col1">-0.000800</td>
<td id="T_a0c6d_row7_col2" class="data row7 col2">0.000400</td>
<td id="T_a0c6d_row7_col3" class="data row7 col3">0.077200</td>
<td id="T_a0c6d_row7_col4" class="data row7 col4">†</td>
</tr>
<tr class="odd">
<td id="T_a0c6d_row8_col0" class="data row8 col0">Theol Ecumenical Rate</td>
<td id="T_a0c6d_row8_col1" class="data row8 col1">0.000900</td>
<td id="T_a0c6d_row8_col2" class="data row8 col2">0.000500</td>
<td id="T_a0c6d_row8_col3" class="data row8 col3">0.104300</td>
<td id="T_a0c6d_row8_col4" class="data row8 col4"></td>
</tr>
<tr class="even">
<td id="T_a0c6d_row9_col0" class="data row9 col0">Theol Modern World Rate</td>
<td id="T_a0c6d_row9_col1" class="data row9 col1">0.000300</td>
<td id="T_a0c6d_row9_col2" class="data row9 col2">0.000600</td>
<td id="T_a0c6d_row9_col3" class="data row9 col3">0.579900</td>
<td id="T_a0c6d_row9_col4" class="data row9 col4"></td>
</tr>
<tr class="odd">
<td id="T_a0c6d_row10_col0" class="data row10 col0">Cosine Sim To Prev</td>
<td id="T_a0c6d_row10_col1" class="data row10 col1">0.032500</td>
<td id="T_a0c6d_row10_col2" class="data row10 col2">0.026400</td>
<td id="T_a0c6d_row10_col3" class="data row10 col3">0.218700</td>
<td id="T_a0c6d_row10_col4" class="data row10 col4"></td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The 1903 transition shows a <em>larger</em> level change in sentence length (+11.9, p &lt; 0.001) and FK grade (+4.0, p &lt; 0.001) than Vatican II does — but in the opposite direction (Pius X’s encyclicals are longer and more complex than Leo XIII’s). This suggests that the stylistic simplification at Vatican II is not unprecedented; earlier papal transitions show comparable or larger stylistic discontinuities. Vatican II is not an outlier even on the surface features.</p>
</section>
<section id="usccb-pastoral-letters-downstream-coherence" class="level3">
<h3 class="anchored" data-anchor-id="usccb-pastoral-letters-downstream-coherence">4.6 USCCB Pastoral Letters: Downstream Coherence</h3>
<p>Because national bishops’ conferences are themselves a product of Vatican II (<em>Christus Dominus</em>, 1965 mandated their formation), the USCCB cannot serve as a pre/post comparison tradition. Instead, it functions as a downstream test: if the council produced institutional rupture, we would expect the newly-created conference’s documents to diverge from papal encyclicals in style and theological emphasis — the “rupture radiating outward” hypothesis.</p>
<p>The evidence does not support divergence. Restricting to full pastoral letters (≥ 2,000 words, n = 8, 1968–2007), USCCB documents track papal encyclicals closely on all three primary stylistic metrics.</p>
<div id="cell-fig-usccb" class="cell" data-execution_count="10">
<div class="cell-output cell-output-display">
<div id="fig-usccb" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-usccb-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-usccb-output-1.png" width="1936" height="669" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-usccb-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: USCCB pastoral letters (teal diamonds) track Catholic encyclicals (red) closely on all three post-Vatican II stylistic metrics. No divergence is visible.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Flesch-Kincaid grades for USCCB letters (range: 12.7–15.4) overlap almost entirely with the encyclical distribution for the same period. Sentence length in both corpora declines gradually across the 1970s–2000s. The cosine similarity panel is noisier — expected given that pastoral letters span diverse topics (peace, economics, environment, race) with no requirement of thematic continuity — but shows no systematic divergence from the encyclical baseline. Rome and the US bishops’ conference are writing in parallel registers post-VII.</p>
</section>
</section>
<section id="v.-discussion" class="level2">
<h2 class="anchored" data-anchor-id="v.-discussion">V. Discussion</h2>
<p>The results support a nuanced reading of the continuity-rupture debate. On surface features — sentence length, reading complexity, register — Vatican II coincides with a real and statistically detectable shift. Encyclicals after 1965 are shorter, simpler, and more accessible. This is consistent with the council’s explicit pastoral orientation and the broader movement toward vernacular liturgy and accessible communication.</p>
<p>But the features that would most directly support the rupture narrative — theological vocabulary, intertextual coherence — move in the wrong direction. The four doctrinal vocabulary clusters (juridical, pastoral, ecumenical, modern world) show no discontinuous shift at 1965. And cosine similarity to the preceding encyclical <em>increases</em> after Vatican II, meaning the corpus becomes more internally consistent, not less. Post-conciliar popes write in ways that are more like each other than pre-conciliar popes were.</p>
<p>The comparison to the SBC is instructive. The Conservative Resurgence produces a sharp, precisely estimated rightward shift in doctrinal formality — FK grade jumps 12 points, resolutions become markedly more legalistic. That is what a genuine institutional rupture looks like in the textual record. Vatican II does not look like that.</p>
<p><strong>Limitations.</strong> The cosine similarity measure is sensitive to document length and corpus composition; cross-tradition comparisons on this metric are unreliable. The Orthodox corpus is small and partly based on paraphrased reconstructions rather than primary translations. The SBC resolution corpus conflates very short documents (median 188 words) where readability metrics are unreliable. A richer analysis would incorporate Latin-language Vatican II documents directly and match document type more carefully across traditions.</p>
</section>
<section id="vi.-conclusion" class="level2">
<h2 class="anchored" data-anchor-id="vi.-conclusion">VI. Conclusion</h2>
<p>Across 1,900 documents and five Christian traditions, the textual evidence does not support the strong rupture claim. Catholic documents simplify stylistically at Vatican II, but theological vocabulary is stable and intertextual coherence <em>increases</em>. The SBC Conservative Resurgence — a genuine institutional rupture by most historical accounts — produces larger and more directionally consistent discontinuities in the textual record than Vatican II does. The hermeneutic of continuity, on the available textual evidence, is closer to the mark.</p>
<hr>
<p><em>Data and replication code available at [GitHub repository]. Corpus scrapers, feature extraction, and model scripts are in <code>scripts/</code>. All models use HC3 heteroskedasticity-robust standard errors.</em></p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>